version: '3.8'

services:
  mongo:
    image: mongo:7.0  # Usa la versión estable que desees
    restart: always
    container_name: mongo_oacsystem
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo_data:
